export const MEDIA_CLICK_CANCEL_THRESHOLD = 6;
export const MEDIA_GAP_PX = 6;
export const MOBILE_MEDIA_QUERY = "(max-width: 760px)";
export const SHORT_MEDIA_FRAME_MIN_EXTRA_PX = 36;
export const SHORT_MEDIA_FRAME_THRESHOLD = 0.72;
export const SAMPLE_CANVAS_SIZE = 24;

export const MEDIA_BACKGROUND_SURFACE_RGB = {
  b: 244,
  g: 247,
  r: 247,
};

const DEFAULT_CLAMPED_TEXT_LINES = 10;
const FALLBACK_ROW_TOP_OFFSET = 64;
const MAIN_TEXT_LINE_HEIGHT_PX = 13 * 1.52;
const BUBBLE_VERTICAL_PADDING_PX = 14 * 2;
const BUBBLE_BORDER_PX = 2;
const ATTACHMENTS_TOP_GAP_PX = 8;
const MEDIA_STRIP_BOTTOM_PADDING_PX = 2;
const BUBBLE_FIT_BREATHING_ROOM_PX = 2;

export const MIN_INLINE_MEDIA_HEIGHT = 140;
export const MOBILE_BOTTOM_SAFE_AREA = 12;
export const DESKTOP_BOTTOM_SAFE_AREA = 40;
export const MEDIA_ROW_TOP_OFFSET = FALLBACK_ROW_TOP_OFFSET;

const BUBBLE_VERTICAL_CHROME_PX =
  BUBBLE_VERTICAL_PADDING_PX +
  BUBBLE_BORDER_PX +
  ATTACHMENTS_TOP_GAP_PX +
  MEDIA_STRIP_BOTTOM_PADDING_PX +
  BUBBLE_FIT_BREATHING_ROOM_PX;

export const BUBBLE_MAX_TEXT_RESERVE_PX =
  MAIN_TEXT_LINE_HEIGHT_PX * DEFAULT_CLAMPED_TEXT_LINES +
  BUBBLE_VERTICAL_CHROME_PX;
